#macro CARD_BASE_WIDTH sprite_get_width(sCardBack)
#macro CARD_BASE_HEIGHT sprite_get_height(sCardBack)


//For the actual size for the GUI
#macro GUI_CARD_HEIGHT (VIEW_HEIGHT/3)
#macro GUI_CARD_WIDTH (GUI_CARD_HEIGHT*0.75)

#macro GUI_CARD_SPRITE_SCALE 2

#macro GUI_CARD_SPRITE_WIDTH GUI_CARD_WIDTH*GUI_CARD_SPRITE_SCALE
#macro GUI_CARD_SPRITE_HEIGHT GUI_CARD_HEIGHT*GUI_CARD_SPRITE_SCALE

//Diplayed card macros
#macro GUI_DISPLAYED_CARD_X VIEW_WIDTH/2
#macro GUI_DISPLAYED_CARD_Y VIEW_HEIGHT/2

#macro GUI_DISPLAYED_CARD_HEIGHT (VIEW_HEIGHT*0.60)
#macro GUI_DISPLAYED_CARD_WIDTH (GUI_DISPLAYED_CARD_HEIGHT*0.75)

//hand positions
#macro GUI_HAND_MARGIN_BOTTOM (VIEW_HEIGHT*0.08)
#macro GUI_HAND_MARGIN_TOP 0
#macro GUI_HAND_MARGIN_SIDE (VIEW_WIDTH - (GUI_CARD_WIDTH)*4.1)/2
#macro GUI_HAND_MAX_WIDTH VIEW_WIDTH-GUI_HAND_MARGIN_SIDE*2

#macro GUI_HAND_BORDER_TOP_Y VIEW_HEIGHT - (GUI_CARD_HEIGHT + GUI_HAND_MARGIN_BOTTOM + GUI_HAND_MARGIN_TOP)*1.25
#macro GUI_HAND_BORDER_BOT_Y VIEW_HEIGHT - GUI_HAND_MARGIN_BOTTOM

//held hand pos
//held
#macro GUI_HAND_MARGIN_SIDE_HELD_CARD (VIEW_WIDTH - GUI_CARD_WIDTH*6.3)/2
#macro GUI_HAND_MAX_WIDTH_HELD_CARD VIEW_WIDTH-GUI_HAND_MARGIN_SIDE_HELD_CARD*2


//Deck macros

#macro GUI_VIEW_DECK_CARD_WIDTH GUI_CARD_WIDTH*0.95//*1.35
#macro GUI_VIEW_DECK_CARD_HEIGHT GUI_CARD_HEIGHT*0.95//*1.35

#macro GUI_VIEW_DECK_SEP CARD_BASE_HEIGHT*0.1

#macro GUI_VIEW_DECK_HEIGHT (VIEW_HEIGHT - GUI_MAP_TOP_MARGIN)
#macro GUI_VIEW_DECK_WIDTH (VIEW_WIDTH*0.7)

#macro GUI_VIEW_DECK_XOFFSET (VIEW_WIDTH - (GUI_VIEW_DECK_WIDTH)) / 2
#macro GUI_VIEW_DECK_YOFFSET 100//GUI_MAP_TOP_MARGIN


#macro DECK_DISPLAYED_CARDS_PER_ROW 4
#macro DECK_RENDERED_CARD_AMMOUNT  ceil((GUI_VIEW_DECK_HEIGHT) / (GUI_VIEW_DECK_SEP+GUI_VIEW_DECK_CARD_HEIGHT))



//in here we can change these vars to ensure text is where it should be
// NOTE origin of the x and y is in the center of the card, so adjust locations for that
#macro CARD_BORDER 6

//Name location
#macro CARD_NAME_MAX_PADDING 0
#macro CARD_NAME_MAX_HEIGHT	30
#macro CARD_NAME_MAX_WIDTH (CARD_BASE_WIDTH * 0.4 - CARD_BORDER)
#macro CARD_NAME_START_X (-CARD_BASE_WIDTH/2 + CARD_BORDER+60)
#macro CARD_NAME_START_Y (-CARD_BASE_HEIGHT/2 + CARD_BORDER+3.5)


//Description 
#macro CARD_DESC_PADDING 4
#macro CARD_DESC_MAX_HEIGHT (100 - (CARD_DESC_PADDING*2))
#macro CARD_DESC_MAX_WIDTH (CARD_BASE_WIDTH - CARD_BORDER * 2 - CARD_DESC_PADDING*2)
#macro CARD_DESC_START_X (CARD_DESC_PADDING + CARD_BORDER-3 - CARD_BASE_WIDTH/2)
#macro CARD_DESC_START_Y (14 + CARD_DESC_PADDING)