#macro GUI_DECK_HEIGHT GUI_CARD_HEIGHT*0.6
#macro GUI_DECK_WIDTH GUI_DECK_HEIGHT*0.75
#macro GUI_DECK_X VIEW_WIDTH-GUI_HAND_MARGIN_SIDE*0.5
#macro GUI_DECK_Y VIEW_HEIGHT - GUI_DECK_HEIGHT*0.8


//Card pos
#macro GUI_CARD_IN_HAND_Y VIEW_HEIGHT - (GUI_CARD_HEIGHT/2 + GUI_HAND_MARGIN_BOTTOM)
#macro GUI_CARD_HIDDEN_Y VIEW_HEIGHT + GUI_CARD_HEIGHT/2 - GUI_CARD_HEIGHT*0.5