enum FINGER_STATE{
	BIOLOGICAL,
	MECHANICAL,
	DESTROYED
}


#macro GUI_HAND_WIDTH VIEW_WIDTH*0.4
#macro GUI_HAND_HEIGHT GUI_HAND_WIDTH

#macro GUI_HAND_HIDDEN_X GUI_HAND_MARGIN_SIDE*1.5 -  GUI_HAND_WIDTH*0.8
#macro GUI_HAND_HIDDEN_Y VIEW_HEIGHT


#macro GUI_HAND_SHOWN_X GUI_HAND_HIDDEN_X
#macro GUI_HAND_SHOWN_Y VIEW_HEIGHT - GUI_HAND_HEIGHT*0.8


#macro GUI_PLAY_CARD_X GUI_CARD_WIDTH*0.7
#macro GUI_PLAY_CARD_Y VIEW_HEIGHT*0.3