
#macro GUI_HAND_WIDTH VIEW_WIDTH*0.2
#macro GUI_HAND_HEIGHT GUI_HAND_WIDTH

#macro GUI_HAND_HIDDEN_X GUI_HAND_MARGIN_SIDE*1.15 -  GUI_HAND_WIDTH
#macro GUI_HAND_HIDDEN_Y VIEW_HEIGHT


#macro GUI_HAND_SHOWN_X GUI_HAND_HIDDEN_X
#macro GUI_HAND_SHOWN_Y VIEW_HEIGHT - GUI_HAND_HEIGHT